# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: step3 --mc --era Run3 --conditions auto:phase1_2021_cosmics --geometry DB:Extended --scenario cosmics --step RAW2DIGI,L1Reco,RECO,SKIM:CosmicSP+CosmicTP --datatier RECO --eventcontent FEVT --filein file:step2.root --fileout file:step3.root --number -1 --runUnscheduled --no_exec
import FWCore.ParameterSet.Config as cms

from Configuration.Eras.Era_Run3_cff import Run3

process = cms.Process('RECO',Run3)

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.EventContent.EventContentCosmics_cff')
process.load('SimGeneral.MixingModule.mixCosmics_cfi')
process.load('Configuration.StandardSequences.GeometryRecoDB_cff')
process.load('Configuration.StandardSequences.MagneticField_cff')
process.load('Configuration.StandardSequences.RawToDigi_cff')
process.load('Configuration.StandardSequences.L1Reco_cff')
process.load('Configuration.StandardSequences.ReconstructionCosmics_cff')
process.load('Configuration.StandardSequences.SkimsCosmics_cff')
process.load('Configuration.StandardSequences.EndOfProcess_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1),
    output = cms.optional.untracked.allowed(cms.int32,cms.PSet)
)

# Input source
process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring('file:step2.root'),
    secondaryFileNames = cms.untracked.vstring()
)

process.options = cms.untracked.PSet(
    FailPath = cms.untracked.vstring(),
    IgnoreCompletely = cms.untracked.vstring(),
    Rethrow = cms.untracked.vstring(),
    SkipEvent = cms.untracked.vstring(),
    allowUnscheduled = cms.obsolete.untracked.bool,
    canDeleteEarly = cms.untracked.vstring(),
    emptyRunLumiMode = cms.obsolete.untracked.string,
    eventSetup = cms.untracked.PSet(
        forceNumberOfConcurrentIOVs = cms.untracked.PSet(

        ),
        numberOfConcurrentIOVs = cms.untracked.uint32(1)
    ),
    fileMode = cms.untracked.string('FULLMERGE'),
    forceEventSetupCacheClearOnNewRun = cms.untracked.bool(False),
    makeTriggerResults = cms.obsolete.untracked.bool,
    numberOfConcurrentLuminosityBlocks = cms.untracked.uint32(1),
    numberOfConcurrentRuns = cms.untracked.uint32(1),
    numberOfStreams = cms.untracked.uint32(0),
    numberOfThreads = cms.untracked.uint32(1),
    printDependencies = cms.untracked.bool(False),
    sizeOfStackForThreadsInKB = cms.optional.untracked.uint32,
    throwIfIllegalParameter = cms.untracked.bool(True),
    wantSummary = cms.untracked.bool(False)
)

# Production Info
process.configurationMetadata = cms.untracked.PSet(
    annotation = cms.untracked.string('step3 nevts:-1'),
    name = cms.untracked.string('Applications'),
    version = cms.untracked.string('$Revision: 1.19 $')
)

# Output definition

process.FEVToutput = cms.OutputModule("PoolOutputModule",
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string('RECO'),
        filterName = cms.untracked.string('')
    ),
    eventAutoFlushCompressedSize = cms.untracked.int32(5242880),
    fileName = cms.untracked.string('file:step3.root'),
    outputCommands = process.FEVTEventContent.outputCommands,
    splitLevel = cms.untracked.int32(0)
)

# Additional output definition
process.SKIMStreamCosmicSP = cms.OutputModule("PoolOutputModule",
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring(
            'cosmicMuonsBarrelOnlyPath', 
            'cosmicMuonsPath', 
            'cosmicMuons1LegPath', 
            'globalCosmicMuonsBarrelOnlyPath', 
            'cosmictrackfinderP5Path', 
            'globalCosmicMuonsPath', 
            'globalCosmicMuons1LegPath'
        )
    ),
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string('RAW-RECO'),
        filterName = cms.untracked.string('CosmicSP')
    ),
    eventAutoFlushCompressedSize = cms.untracked.int32(5242880),
    fileName = cms.untracked.string('CosmicSP.root'),
    outputCommands = cms.untracked.vstring( (
        'drop *', 
        'keep *_logErrorHarvester_*_*', 
        'drop *', 
        'keep  FEDRawDataCollection_rawDataCollector_*_*', 
        'keep  FEDRawDataCollection_source_*_*', 
        'keep *_cscTriggerPrimitiveDigis_*_*', 
        'keep *_dtTriggerPrimitiveDigis_*_*', 
        'keep *_rpcTriggerDigis_*_*', 
        'keep *_rctDigis_*_*', 
        'keep *_csctfDigis_*_*', 
        'keep *_csctfTrackDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_gctDigis_*_*', 
        'keep *_gmtDigis_*_*', 
        'keep *_gtDigis_*_*', 
        'keep *_gtEvmDigis_*_*', 
        'keep *_l1GtRecord_*_*', 
        'keep *_l1GtObjectMap_*_*', 
        'keep *_l1extraParticles_*_*', 
        'drop *_hlt*_*_*', 
        'keep FEDRawDataCollection_rawDataCollector_*_*', 
        'keep FEDRawDataCollection_source_*_*', 
        'keep GlobalObjectMapRecord_hltGtStage2ObjectMap_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep triggerTriggerEvent_*_*_*', 
        'keep *_hltFEDSelectorL1_*_*', 
        'keep *_hltScoutingCaloPacker_*_*', 
        'keep *_hltScoutingEgammaPacker_*_*', 
        'keep *_hltScoutingMuonPackerCalo_*_*', 
        'keep *_hltScoutingMuonPacker_*_*', 
        'keep *_hltScoutingPFPacker_*_*', 
        'keep *_hltScoutingPrimaryVertexPackerCaloMuon_*_*', 
        'keep *_hltScoutingPrimaryVertexPacker_*_*', 
        'keep *_hltScoutingTrackPacker_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep PixelDigiedmDetSetVector_siPixelDigis_*_*', 
        'keep *_siStripDigis_*_*', 
        'keep *_siStripZeroSuppression_*_*', 
        'keep *_siPixelClusters_*_*', 
        'keep *_siStripClusters_*_*', 
        'keep *_siPixelRecHits_*_*', 
        'keep *_siStripRecHits_*_*', 
        'keep *_siStripMatchedRecHits_*_*', 
        'keep *_muonDTDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_dt1DRecHits_*_*', 
        'keep *_dt4DSegments_*_*', 
        'keep *_dt4DSegmentsT0Seg_*_*', 
        'keep *_csc2DRecHits_*_*', 
        'keep *_cscSegments_*_*', 
        'keep RPCDetIdRPCDigiMuonDigiCollection_muonRPCDigis_*_*', 
        'keep *_rpcRecHits_*_*', 
        'keep *_gemRecHits_*_*', 
        'keep *_gemSegments_*_*', 
        'keep *_hbhereco_*_*', 
        'keep *_hfprereco_*_*', 
        'keep *_hfreco_*_*', 
        'keep *_horeco_*_*', 
        'keep HBHERecHitsSorted_hbherecoMB_*_*', 
        'keep HORecHitsSorted_horecoMB_*_*', 
        'keep HFRecHitsSorted_hfrecoMB_*_*', 
        'keep ZDCDataFramesSorted_hcalDigis_*_*', 
        'keep ZDCDataFramesSorted_castorDigis_*_*', 
        'keep ZDCDataFramesSorted_simHcalUnsuppressedDigis_*_*', 
        'keep ZDCRecHitsSorted_zdcreco_*_*', 
        'keep HcalUnpackerReport_castorDigis_*_*', 
        'keep HcalUnpackerReport_hcalDigis_*_*', 
        'keep *_ecalPreshowerRecHit_*_*', 
        'keep *_ecalRecHit_*_*', 
        'keep *_ecalCompactTrigPrim_*_*', 
        'keep ESDataFramesSorted_ecalPreshowerDigis_*_*', 
        'keep EBSrFlagsSorted_ecalDigis__*', 
        'keep EESrFlagsSorted_ecalDigis__*', 
        'keep *_uncleanedHybridSuperClusters_*_*', 
        'keep *_correctedFixedMatrixSuperClustersWithPreshower_*_*', 
        'keep *_correctedEndcapSuperClustersWithPreshower_*_*', 
        'keep *_islandBasicClusters_*_*', 
        'keep *_fixedMatrixBasicClusters_*_*', 
        'keep *_cosmicBasicClusters_*_*', 
        'keep *_cosmicSuperClusters_*_*', 
        'keep recoCaloClusters_hybridSuperClusters_*_*', 
        'keep recoSuperClusters_islandSuperClusters_islandBarrelSuperClusters_*', 
        'keep recoSuperClusters_correctedHybridSuperClusters_*_*', 
        'keep recoSuperClusters_correctedEndcapSuperClustersWithPreshower_*_*', 
        'keep recoPreshowerClusters_fixedMatrixSuperClustersWithPreshower_*_*', 
        'keep recoSuperClusters_correctedFixedMatrixSuperClustersWithPreshower_*_*', 
        'keep recoPreshowerClusterShapes_preshowerClusterShape_*_*', 
        'keep recoPreshowerClusterShapes_fixedMatrixPreshowerClusterShape_*_*', 
        'keep *_gedPhotonCore_*_*', 
        'keep *_gedPhotons_*_*', 
        'keep recoPhotons_mustachePhotons_*_*', 
        'keep recoPhotonCores_mustachePhotonCore_*_*', 
        'keep recoTrackExtras_ckfOutInTracksFromConversions_*_*', 
        'keep recoTrackExtras_ckfInOutTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_ckfOutInTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_ckfInOutTracksFromConversions_*_*', 
        'keep recoTrackExtras_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep recoTrackExtras_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep recoGsfElectronCores_gsfElectronCores_*_*', 
        'keep recoGsfElectronCores_gedGsfElectronCores_*_*', 
        'keep recoGsfElectrons_gsfElectrons_*_*', 
        'keep recoGsfElectrons_gedGsfElectrons_*_*', 
        'keep recoGsfElectronCores_uncleanedOnlyGsfElectronCores_*_*', 
        'keep recoGsfElectrons_uncleanedOnlyGsfElectrons_*_*', 
        'keep floatedmValueMap_eidRobustLoose_*_*', 
        'keep floatedmValueMap_eidRobustTight_*_*', 
        'keep floatedmValueMap_eidRobustHighEnergy_*_*', 
        'keep floatedmValueMap_eidLoose_*_*', 
        'keep floatedmValueMap_eidTight_*_*', 
        'keep *_egmGedGsfElectronPFIsolation_*_*', 
        'keep recoPhotonCores_gedPhotonCore_*_*', 
        'keep recoPhotons_gedPhotons_*_*', 
        'keep *_particleBasedIsolation_*_*', 
        'keep recoPhotonCores_photonCore_*_*', 
        'keep recoPhotons_photons_*_*', 
        'keep recoPhotonCores_ootPhotonCore_*_*', 
        'keep recoPhotons_ootPhotons_*_*', 
        'keep recoConversions_conversions_*_*', 
        'drop recoConversions_conversions_uncleanedConversions_*', 
        'keep recoConversions_mustacheConversions_*_*', 
        'keep *_gsfTracksOpenConversions_*_*', 
        'keep recoConversions_allConversions_*_*', 
        'keep recoConversions_allConversionsOldEG_*_*', 
        'keep recoTracks_ckfOutInTracksFromConversions_*_*', 
        'keep recoTracks_ckfInOutTracksFromConversions_*_*', 
        'keep recoConversions_uncleanedOnlyAllConversions_*_*', 
        'keep recoTracks_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep recoTracks_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep *_PhotonIDProd_*_*', 
        'keep *_PhotonIDProdGED_*_*', 
        'keep *_hfRecoEcalCandidate_*_*', 
        'keep *_hfEMClusters_*_*', 
        'keep *_gedGsfElectronCores_*_*', 
        'keep *_gedGsfElectrons_*_*', 
        'keep recoCaloClusters_lowPtGsfElectronSuperClusters_*_*', 
        'keep recoGsfElectrons_lowPtGsfElectrons_*_*', 
        'keep recoGsfElectronCores_lowPtGsfElectronCores_*_*', 
        'keep recoGsfTracks_lowPtGsfEleGsfTracks_*_*', 
        'keep *_lowPtGsfToTrackLinks_*_*', 
        'keep recoSuperClusters_lowPtGsfElectronSuperClusters_*_*', 
        'keep floatedmValueMap_lowPtGsfElectronSeedValueMaps_*_*', 
        'keep floatedmValueMap_lowPtGsfElectronID_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5_*_*', 
        'keep recoTrackExtras_beamhaloTracks_*_*', 
        'keep TrackingRecHitsOwned_beamhaloTracks_*_*', 
        'keep recoTrackExtras_splittedTracksP5_*_*', 
        'keep TrackingRecHitsOwned_splittedTracksP5_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5Top_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5Top_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5Top_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5Top_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5Top_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5Top_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5Bottom_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5Bottom_*_*', 
        'keep recoTrackExtras_regionalCosmicTracks_*_*', 
        'keep TrackingRecHitsOwned_regionalCosmicTracks_*_*', 
        'keep *_dedxTruncated40_*_*', 
        'keep *_dedxTruncated40CTF_*_*', 
        'keep *_dedxTruncated40CosmicTF_*_*', 
        'keep recoTracks_cosmicDCTracks_*_*', 
        'keep recoTrackExtras_cosmicDCTracks_*_*', 
        'keep TrackingRecHitsOwned_cosmicDCTracks_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5_*_*', 
        'keep recoTracks_cosmictrackfinderP5_*_*', 
        'keep recoTracks_beamhaloTracks_*_*', 
        'keep recoTracks_splittedTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5Top_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5Top_*_*', 
        'keep recoTracks_cosmictrackfinderP5Top_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5Bottom_*_*', 
        'keep recoTracks_cosmictrackfinderP5Bottom_*_*', 
        'keep recoTracks_regionalCosmicTracks_*_*', 
        'keep *_dedxHitInfo_*_*', 
        'keep *_dedxHarmonic2_*_*', 
        'keep *_dedxHitInfoCTF_*_*', 
        'keep *_dedxHarmonic2CTF_*_*', 
        'keep *_dedxHitInfoCosmicTF_*_*', 
        'keep *_dedxHarmonic2CosmicTF_*_*', 
        'keep *_ak4CaloJets_*_*', 
        'keep *_ak4PFJets_*_*', 
        'keep *_ak4TrackJets_*_*', 
        'keep recoRecoChargedRefCandidates_trackRefsForJets_*_*', 
        'keep *_towerMaker_*_*', 
        'keep *_ak4JetTracksAssociatorAtCaloFace_*_*', 
        'keep *_ak5CastorJets_*_*', 
        'keep *_ak7CastorJets_*_*', 
        'keep recoCaloJets_ak4CaloJets_*_*', 
        'keep *_ak4CaloJets_rho_*', 
        'keep *_ak4CaloJets_sigma_*', 
        'keep *_ak4PFJetsCHS_*_*', 
        'keep floatedmValueMap_puppi_*_*', 
        'keep *_ak4PFJetsPuppi_*_*', 
        'keep *_ak8PFJetsPuppi_*_*', 
        'keep *_ak8PFJetsPuppiSoftDrop_*_*', 
        'keep recoPFJets_ak4PFJets_*_*', 
        'keep *_ak4PFJets_rho_*', 
        'keep *_ak4PFJets_sigma_*', 
        'keep *_JetPlusTrackZSPCorJetAntiKt4_*_*', 
        'keep *_caloTowers_*_*', 
        'keep *_CastorTowerReco_*_*', 
        'keep *_ak4JetTracksAssociatorAtVertex_*_*', 
        'keep *_ak4JetTracksAssociatorAtVertexPF_*_*', 
        'keep *_ak4JetTracksAssociatorExplicit_*_*', 
        'keep *_ak4JetExtender_*_*', 
        'keep *_ak4JetID_*_*', 
        'keep recoBasicJets_ak5CastorJets_*_*', 
        'keep *_ak5CastorJets_rho_*', 
        'keep *_ak5CastorJets_sigma_*', 
        'keep *_ak5CastorJetID_*_*', 
        'keep recoBasicJets_ak7CastorJets_*_*', 
        'keep *_ak7CastorJets_rho_*', 
        'keep *_ak7CastorJets_sigma_*', 
        'keep *_ak7CastorJetID_*_*', 
        'keep *_fixedGridRhoAll_*_*', 
        'keep *_fixedGridRhoFastjetAll_*_*', 
        'keep *_fixedGridRhoFastjetAllTmp_*_*', 
        'keep *_fixedGridRhoFastjetCentral_*_*', 
        'keep *_fixedGridRhoFastjetAllCalo_*_*', 
        'keep *_fixedGridRhoFastjetCentralCalo_*_*', 
        'keep *_fixedGridRhoFastjetCentralChargedPileUp_*_*', 
        'keep *_fixedGridRhoFastjetCentralNeutral_*_*', 
        'keep *_ak8PFJetsPuppiSoftDropMass_*_*', 
        'keep recoHcalNoiseRBXs_hcalnoise_*_*', 
        'keep recoEcalHaloData_EcalHaloData_*_*', 
        'keep recoHcalHaloData_HcalHaloData_*_*', 
        'keep recoCaloMETs_caloMet_*_*', 
        'keep recoCaloMETs_caloMetBE_*_*', 
        'keep recoCaloMETs_caloMetBEFO_*_*', 
        'keep recoCaloMETs_caloMetM_*_*', 
        'keep recoPFMETs_pfMet_*_*', 
        'keep recoPFMETs_pfChMet_*_*', 
        'keep floatedmValueMap_puppiNoLep_*_*', 
        'keep recoPFMETs_pfMetPuppi_*_*', 
        'keep recoMuonMETCorrectionDataedmValueMap_muonMETValueMapProducer_*_*', 
        'keep HcalNoiseSummary_hcalnoise_*_*', 
        'keep recoGlobalHaloData_GlobalHaloData_*_*', 
        'keep recoCSCHaloData_CSCHaloData_*_*', 
        'keep recoBeamHaloSummary_BeamHaloSummary_*_*', 
        'keep *_CosmicMuonSeed_*_*', 
        'keep *_CosmicMuonSeedEndCapsOnly_*_*', 
        'keep *_CosmicMuonSeedWitht0Correction_*_*', 
        'keep *_ancientMuonSeed_*_*', 
        'keep recoTracks_cosmicMuons_*_*', 
        'keep recoTrackExtras_cosmicMuons_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuons_*_*', 
        'keep recoTracks_globalCosmicMuons_*_*', 
        'keep recoTrackExtras_globalCosmicMuons_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuons_*_*', 
        'keep recoTracks_tevMuons_*_*', 
        'keep recoTrackExtras_tevMuons_*_*', 
        'keep recoTracksToOnerecoTracksAssociation_tevMuons_*_*', 
        'keep recoMuons_muons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muons_*_*', 
        'keep recoTracks_globalCosmicSplitMuons_*_*', 
        'keep recoTrackExtras_globalCosmicSplitMuons_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicSplitMuons_*_*', 
        'keep recoMuons_splitMuons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_splitMuons_*_*', 
        'keep recoTracks_cosmicMuonsNoRPC_*_*', 
        'keep recoTrackExtras_cosmicMuonsNoRPC_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsNoRPC_*_*', 
        'keep recoTracks_globalCosmicMuonsNoRPC_*_*', 
        'keep recoTrackExtras_globalCosmicMuonsNoRPC_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuonsNoRPC_*_*', 
        'keep recoMuons_muonsNoRPC_*_*', 
        'keep recoTracks_cosmicMuons1Leg_*_*', 
        'keep recoTrackExtras_cosmicMuons1Leg_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuons1Leg_*_*', 
        'keep recoTracks_globalCosmicMuons1Leg_*_*', 
        'keep recoTrackExtras_globalCosmicMuons1Leg_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuons1Leg_*_*', 
        'keep recoMuons_muons1Leg_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muons1Leg_*_*', 
        'keep recoTracks_cosmicMuonsWitht0Correction_*_*', 
        'keep recoTrackExtras_cosmicMuonsWitht0Correction_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsWitht0Correction_*_*', 
        'keep recoTracks_globalCosmicMuonsWitht0Correction_*_*', 
        'keep recoTrackExtras_globalCosmicMuonsWitht0Correction_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuonsWitht0Correction_*_*', 
        'keep recoMuons_muonsWitht0Correction_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muonsWitht0Correction_*_*', 
        'keep recoTracks_cosmicMuonsEndCapsOnly_*_*', 
        'keep recoTrackExtras_cosmicMuonsEndCapsOnly_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsEndCapsOnly_*_*', 
        'keep recoTracks_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep recoTrackExtras_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep TrackingRecHitsOwned_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep recoMuons_muonsBeamHaloEndCapsOnly_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muonsBeamHaloEndCapsOnly_*_*', 
        'keep recoTracks_standAloneMuons_*_*', 
        'keep recoTrackExtras_standAloneMuons_*_*', 
        'keep TrackingRecHitsOwned_standAloneMuons_*_*', 
        'keep recoMuons_lhcSTAMuons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_lhcSTAMuons_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksBeamHaloMuon_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep *_muIsoDepositTk_*_*', 
        'keep *_muIsoDepositCalByAssociatorTowers_*_*', 
        'keep *_muIsoDepositCalByAssociatorHits_*_*', 
        'keep *_muIsoDepositJets_*_*', 
        'keep *_muGlobalIsoDepositCtfTk_*_*', 
        'keep *_muGlobalIsoDepositCalByAssociatorTowers_*_*', 
        'keep *_muGlobalIsoDepositCalByAssociatorHits_*_*', 
        'keep *_muGlobalIsoDepositJets_*_*', 
        'keep *_offlineBeamSpot_*_*', 
        'keep  *_offlinePrimaryVertices__*', 
        'keep *_offlinePrimaryVerticesWithBS_*_*', 
        'keep *_offlinePrimaryVerticesFromCosmicTracks_*_*', 
        'keep *_nuclearInteractionMaker_*_*', 
        'keep *_generalV0Candidates_*_*', 
        'keep *_inclusiveSecondaryVertices_*_*', 
        'keep *_cscTriggerPrimitiveDigis_*_*', 
        'keep *_dtTriggerPrimitiveDigis_*_*', 
        'keep *_rpcTriggerDigis_*_*', 
        'keep *_rctDigis_*_*', 
        'keep *_csctfDigis_*_*', 
        'keep *_csctfTrackDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_gctDigis_*_*', 
        'keep *_gmtDigis_*_*', 
        'keep *_gtDigis_*_*', 
        'keep *_gtEvmDigis_*_*', 
        'keep *_l1GtRecord_*_*', 
        'keep *_l1GtTriggerMenuLite_*_*', 
        'keep *_l1GtObjectMap_*_*', 
        'keep *_l1extraParticles_*_*', 
        'keep *_l1L1GtObjectMap_*_*', 
        'keep LumiDetails_lumiProducer_*_*', 
        'keep LumiSummary_lumiProducer_*_*', 
        'drop *_hlt*_*_*', 
        'keep GlobalObjectMapRecord_hltGtStage2ObjectMap_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep triggerTriggerEvent_*_*_*', 
        'keep *_hltFEDSelectorL1_*_*', 
        'keep *_hltScoutingCaloPacker_*_*', 
        'keep *_hltScoutingEgammaPacker_*_*', 
        'keep *_hltScoutingMuonPackerCalo_*_*', 
        'keep *_hltScoutingMuonPacker_*_*', 
        'keep *_hltScoutingPFPacker_*_*', 
        'keep *_hltScoutingPrimaryVertexPackerCaloMuon_*_*', 
        'keep *_hltScoutingPrimaryVertexPacker_*_*', 
        'keep *_hltScoutingTrackPacker_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep L1AcceptBunchCrossings_scalersRawToDigi_*_*', 
        'keep L1TriggerScalerss_scalersRawToDigi_*_*', 
        'keep Level1TriggerScalerss_scalersRawToDigi_*_*', 
        'keep LumiScalerss_scalersRawToDigi_*_*', 
        'keep BeamSpotOnlines_scalersRawToDigi_*_*', 
        'keep DcsStatuss_scalersRawToDigi_*_*', 
        'keep DcsStatuss_hltScalersRawToDigi_*_*', 
        'keep CTPPSRecord_onlineMetaDataDigis_*_*', 
        'keep DCSRecord_onlineMetaDataDigis_*_*', 
        'keep OnlineLuminosityRecord_onlineMetaDataDigis_*_*', 
        'keep recoBeamSpot_onlineMetaDataDigis_*_*', 
        'keep *_tcdsDigis_*_*', 
        'drop *_MEtoEDMConverter_*_*', 
        'drop *_*_*_SKIM'
     ) )
)
process.SKIMStreamCosmicTP = cms.OutputModule("PoolOutputModule",
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring(
            'cosmicMuonsBarrelOnlyTkPath', 
            'cosmicMuonsEndCapsOnlyTkPath', 
            'cosmicMuonsTkPath', 
            'cosmicMuons1LegTkPath', 
            'globalCosmicMuonsBarrelOnlyTkPath', 
            'globalCosmicMuonsEndCapsOnlyTkPath', 
            'globalCosmicMuonsTkPath', 
            'globalCosmicMuons1LegTkPath', 
            'cosmictrackfinderP5TkCntPath', 
            'ctfWithMaterialTracksP5TkCntPath'
        )
    ),
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string('RAW-RECO'),
        filterName = cms.untracked.string('CosmicTP')
    ),
    eventAutoFlushCompressedSize = cms.untracked.int32(5242880),
    fileName = cms.untracked.string('CosmicTP.root'),
    outputCommands = cms.untracked.vstring( (
        'drop *', 
        'keep *_logErrorHarvester_*_*', 
        'drop *', 
        'keep  FEDRawDataCollection_rawDataCollector_*_*', 
        'keep  FEDRawDataCollection_source_*_*', 
        'keep *_cscTriggerPrimitiveDigis_*_*', 
        'keep *_dtTriggerPrimitiveDigis_*_*', 
        'keep *_rpcTriggerDigis_*_*', 
        'keep *_rctDigis_*_*', 
        'keep *_csctfDigis_*_*', 
        'keep *_csctfTrackDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_gctDigis_*_*', 
        'keep *_gmtDigis_*_*', 
        'keep *_gtDigis_*_*', 
        'keep *_gtEvmDigis_*_*', 
        'keep *_l1GtRecord_*_*', 
        'keep *_l1GtObjectMap_*_*', 
        'keep *_l1extraParticles_*_*', 
        'drop *_hlt*_*_*', 
        'keep FEDRawDataCollection_rawDataCollector_*_*', 
        'keep FEDRawDataCollection_source_*_*', 
        'keep GlobalObjectMapRecord_hltGtStage2ObjectMap_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep triggerTriggerEvent_*_*_*', 
        'keep *_hltFEDSelectorL1_*_*', 
        'keep *_hltScoutingCaloPacker_*_*', 
        'keep *_hltScoutingEgammaPacker_*_*', 
        'keep *_hltScoutingMuonPackerCalo_*_*', 
        'keep *_hltScoutingMuonPacker_*_*', 
        'keep *_hltScoutingPFPacker_*_*', 
        'keep *_hltScoutingPrimaryVertexPackerCaloMuon_*_*', 
        'keep *_hltScoutingPrimaryVertexPacker_*_*', 
        'keep *_hltScoutingTrackPacker_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep PixelDigiedmDetSetVector_siPixelDigis_*_*', 
        'keep *_siStripDigis_*_*', 
        'keep *_siStripZeroSuppression_*_*', 
        'keep *_siPixelClusters_*_*', 
        'keep *_siStripClusters_*_*', 
        'keep *_siPixelRecHits_*_*', 
        'keep *_siStripRecHits_*_*', 
        'keep *_siStripMatchedRecHits_*_*', 
        'keep *_muonDTDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_dt1DRecHits_*_*', 
        'keep *_dt4DSegments_*_*', 
        'keep *_dt4DSegmentsT0Seg_*_*', 
        'keep *_csc2DRecHits_*_*', 
        'keep *_cscSegments_*_*', 
        'keep RPCDetIdRPCDigiMuonDigiCollection_muonRPCDigis_*_*', 
        'keep *_rpcRecHits_*_*', 
        'keep *_gemRecHits_*_*', 
        'keep *_gemSegments_*_*', 
        'keep *_hbhereco_*_*', 
        'keep *_hfprereco_*_*', 
        'keep *_hfreco_*_*', 
        'keep *_horeco_*_*', 
        'keep HBHERecHitsSorted_hbherecoMB_*_*', 
        'keep HORecHitsSorted_horecoMB_*_*', 
        'keep HFRecHitsSorted_hfrecoMB_*_*', 
        'keep ZDCDataFramesSorted_hcalDigis_*_*', 
        'keep ZDCDataFramesSorted_castorDigis_*_*', 
        'keep ZDCDataFramesSorted_simHcalUnsuppressedDigis_*_*', 
        'keep ZDCRecHitsSorted_zdcreco_*_*', 
        'keep HcalUnpackerReport_castorDigis_*_*', 
        'keep HcalUnpackerReport_hcalDigis_*_*', 
        'keep *_ecalPreshowerRecHit_*_*', 
        'keep *_ecalRecHit_*_*', 
        'keep *_ecalCompactTrigPrim_*_*', 
        'keep ESDataFramesSorted_ecalPreshowerDigis_*_*', 
        'keep EBSrFlagsSorted_ecalDigis__*', 
        'keep EESrFlagsSorted_ecalDigis__*', 
        'keep *_uncleanedHybridSuperClusters_*_*', 
        'keep *_correctedFixedMatrixSuperClustersWithPreshower_*_*', 
        'keep *_correctedEndcapSuperClustersWithPreshower_*_*', 
        'keep *_islandBasicClusters_*_*', 
        'keep *_fixedMatrixBasicClusters_*_*', 
        'keep *_cosmicBasicClusters_*_*', 
        'keep *_cosmicSuperClusters_*_*', 
        'keep recoCaloClusters_hybridSuperClusters_*_*', 
        'keep recoSuperClusters_islandSuperClusters_islandBarrelSuperClusters_*', 
        'keep recoSuperClusters_correctedHybridSuperClusters_*_*', 
        'keep recoSuperClusters_correctedEndcapSuperClustersWithPreshower_*_*', 
        'keep recoPreshowerClusters_fixedMatrixSuperClustersWithPreshower_*_*', 
        'keep recoSuperClusters_correctedFixedMatrixSuperClustersWithPreshower_*_*', 
        'keep recoPreshowerClusterShapes_preshowerClusterShape_*_*', 
        'keep recoPreshowerClusterShapes_fixedMatrixPreshowerClusterShape_*_*', 
        'keep *_gedPhotonCore_*_*', 
        'keep *_gedPhotons_*_*', 
        'keep recoPhotons_mustachePhotons_*_*', 
        'keep recoPhotonCores_mustachePhotonCore_*_*', 
        'keep recoTrackExtras_ckfOutInTracksFromConversions_*_*', 
        'keep recoTrackExtras_ckfInOutTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_ckfOutInTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_ckfInOutTracksFromConversions_*_*', 
        'keep recoTrackExtras_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep recoTrackExtras_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep TrackingRecHitsOwned_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep recoGsfElectronCores_gsfElectronCores_*_*', 
        'keep recoGsfElectronCores_gedGsfElectronCores_*_*', 
        'keep recoGsfElectrons_gsfElectrons_*_*', 
        'keep recoGsfElectrons_gedGsfElectrons_*_*', 
        'keep recoGsfElectronCores_uncleanedOnlyGsfElectronCores_*_*', 
        'keep recoGsfElectrons_uncleanedOnlyGsfElectrons_*_*', 
        'keep floatedmValueMap_eidRobustLoose_*_*', 
        'keep floatedmValueMap_eidRobustTight_*_*', 
        'keep floatedmValueMap_eidRobustHighEnergy_*_*', 
        'keep floatedmValueMap_eidLoose_*_*', 
        'keep floatedmValueMap_eidTight_*_*', 
        'keep *_egmGedGsfElectronPFIsolation_*_*', 
        'keep recoPhotonCores_gedPhotonCore_*_*', 
        'keep recoPhotons_gedPhotons_*_*', 
        'keep *_particleBasedIsolation_*_*', 
        'keep recoPhotonCores_photonCore_*_*', 
        'keep recoPhotons_photons_*_*', 
        'keep recoPhotonCores_ootPhotonCore_*_*', 
        'keep recoPhotons_ootPhotons_*_*', 
        'keep recoConversions_conversions_*_*', 
        'drop recoConversions_conversions_uncleanedConversions_*', 
        'keep recoConversions_mustacheConversions_*_*', 
        'keep *_gsfTracksOpenConversions_*_*', 
        'keep recoConversions_allConversions_*_*', 
        'keep recoConversions_allConversionsOldEG_*_*', 
        'keep recoTracks_ckfOutInTracksFromConversions_*_*', 
        'keep recoTracks_ckfInOutTracksFromConversions_*_*', 
        'keep recoConversions_uncleanedOnlyAllConversions_*_*', 
        'keep recoTracks_uncleanedOnlyCkfOutInTracksFromConversions_*_*', 
        'keep recoTracks_uncleanedOnlyCkfInOutTracksFromConversions_*_*', 
        'keep *_PhotonIDProd_*_*', 
        'keep *_PhotonIDProdGED_*_*', 
        'keep *_hfRecoEcalCandidate_*_*', 
        'keep *_hfEMClusters_*_*', 
        'keep *_gedGsfElectronCores_*_*', 
        'keep *_gedGsfElectrons_*_*', 
        'keep recoCaloClusters_lowPtGsfElectronSuperClusters_*_*', 
        'keep recoGsfElectrons_lowPtGsfElectrons_*_*', 
        'keep recoGsfElectronCores_lowPtGsfElectronCores_*_*', 
        'keep recoGsfTracks_lowPtGsfEleGsfTracks_*_*', 
        'keep *_lowPtGsfToTrackLinks_*_*', 
        'keep recoSuperClusters_lowPtGsfElectronSuperClusters_*_*', 
        'keep floatedmValueMap_lowPtGsfElectronSeedValueMaps_*_*', 
        'keep floatedmValueMap_lowPtGsfElectronID_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5_*_*', 
        'keep recoTrackExtras_beamhaloTracks_*_*', 
        'keep TrackingRecHitsOwned_beamhaloTracks_*_*', 
        'keep recoTrackExtras_splittedTracksP5_*_*', 
        'keep TrackingRecHitsOwned_splittedTracksP5_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5Top_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5Top_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5Top_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5Top_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5Top_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5Top_*_*', 
        'keep recoTrackExtras_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep recoTrackExtras_rsWithMaterialTracksP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_rsWithMaterialTracksP5Bottom_*_*', 
        'keep recoTrackExtras_cosmictrackfinderP5Bottom_*_*', 
        'keep TrackingRecHitsOwned_cosmictrackfinderP5Bottom_*_*', 
        'keep recoTrackExtras_regionalCosmicTracks_*_*', 
        'keep TrackingRecHitsOwned_regionalCosmicTracks_*_*', 
        'keep *_dedxTruncated40_*_*', 
        'keep *_dedxTruncated40CTF_*_*', 
        'keep *_dedxTruncated40CosmicTF_*_*', 
        'keep recoTracks_cosmicDCTracks_*_*', 
        'keep recoTrackExtras_cosmicDCTracks_*_*', 
        'keep TrackingRecHitsOwned_cosmicDCTracks_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5_*_*', 
        'keep recoTracks_cosmictrackfinderP5_*_*', 
        'keep recoTracks_beamhaloTracks_*_*', 
        'keep recoTracks_splittedTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5Top_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5Top_*_*', 
        'keep recoTracks_cosmictrackfinderP5Top_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5Bottom_*_*', 
        'keep recoTracks_rsWithMaterialTracksP5Bottom_*_*', 
        'keep recoTracks_cosmictrackfinderP5Bottom_*_*', 
        'keep recoTracks_regionalCosmicTracks_*_*', 
        'keep *_dedxHitInfo_*_*', 
        'keep *_dedxHarmonic2_*_*', 
        'keep *_dedxHitInfoCTF_*_*', 
        'keep *_dedxHarmonic2CTF_*_*', 
        'keep *_dedxHitInfoCosmicTF_*_*', 
        'keep *_dedxHarmonic2CosmicTF_*_*', 
        'keep *_ak4CaloJets_*_*', 
        'keep *_ak4PFJets_*_*', 
        'keep *_ak4TrackJets_*_*', 
        'keep recoRecoChargedRefCandidates_trackRefsForJets_*_*', 
        'keep *_towerMaker_*_*', 
        'keep *_ak4JetTracksAssociatorAtCaloFace_*_*', 
        'keep *_ak5CastorJets_*_*', 
        'keep *_ak7CastorJets_*_*', 
        'keep recoCaloJets_ak4CaloJets_*_*', 
        'keep *_ak4CaloJets_rho_*', 
        'keep *_ak4CaloJets_sigma_*', 
        'keep *_ak4PFJetsCHS_*_*', 
        'keep floatedmValueMap_puppi_*_*', 
        'keep *_ak4PFJetsPuppi_*_*', 
        'keep *_ak8PFJetsPuppi_*_*', 
        'keep *_ak8PFJetsPuppiSoftDrop_*_*', 
        'keep recoPFJets_ak4PFJets_*_*', 
        'keep *_ak4PFJets_rho_*', 
        'keep *_ak4PFJets_sigma_*', 
        'keep *_JetPlusTrackZSPCorJetAntiKt4_*_*', 
        'keep *_caloTowers_*_*', 
        'keep *_CastorTowerReco_*_*', 
        'keep *_ak4JetTracksAssociatorAtVertex_*_*', 
        'keep *_ak4JetTracksAssociatorAtVertexPF_*_*', 
        'keep *_ak4JetTracksAssociatorExplicit_*_*', 
        'keep *_ak4JetExtender_*_*', 
        'keep *_ak4JetID_*_*', 
        'keep recoBasicJets_ak5CastorJets_*_*', 
        'keep *_ak5CastorJets_rho_*', 
        'keep *_ak5CastorJets_sigma_*', 
        'keep *_ak5CastorJetID_*_*', 
        'keep recoBasicJets_ak7CastorJets_*_*', 
        'keep *_ak7CastorJets_rho_*', 
        'keep *_ak7CastorJets_sigma_*', 
        'keep *_ak7CastorJetID_*_*', 
        'keep *_fixedGridRhoAll_*_*', 
        'keep *_fixedGridRhoFastjetAll_*_*', 
        'keep *_fixedGridRhoFastjetAllTmp_*_*', 
        'keep *_fixedGridRhoFastjetCentral_*_*', 
        'keep *_fixedGridRhoFastjetAllCalo_*_*', 
        'keep *_fixedGridRhoFastjetCentralCalo_*_*', 
        'keep *_fixedGridRhoFastjetCentralChargedPileUp_*_*', 
        'keep *_fixedGridRhoFastjetCentralNeutral_*_*', 
        'keep *_ak8PFJetsPuppiSoftDropMass_*_*', 
        'keep recoHcalNoiseRBXs_hcalnoise_*_*', 
        'keep recoEcalHaloData_EcalHaloData_*_*', 
        'keep recoHcalHaloData_HcalHaloData_*_*', 
        'keep recoCaloMETs_caloMet_*_*', 
        'keep recoCaloMETs_caloMetBE_*_*', 
        'keep recoCaloMETs_caloMetBEFO_*_*', 
        'keep recoCaloMETs_caloMetM_*_*', 
        'keep recoPFMETs_pfMet_*_*', 
        'keep recoPFMETs_pfChMet_*_*', 
        'keep floatedmValueMap_puppiNoLep_*_*', 
        'keep recoPFMETs_pfMetPuppi_*_*', 
        'keep recoMuonMETCorrectionDataedmValueMap_muonMETValueMapProducer_*_*', 
        'keep HcalNoiseSummary_hcalnoise_*_*', 
        'keep recoGlobalHaloData_GlobalHaloData_*_*', 
        'keep recoCSCHaloData_CSCHaloData_*_*', 
        'keep recoBeamHaloSummary_BeamHaloSummary_*_*', 
        'keep *_CosmicMuonSeed_*_*', 
        'keep *_CosmicMuonSeedEndCapsOnly_*_*', 
        'keep *_CosmicMuonSeedWitht0Correction_*_*', 
        'keep *_ancientMuonSeed_*_*', 
        'keep recoTracks_cosmicMuons_*_*', 
        'keep recoTrackExtras_cosmicMuons_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuons_*_*', 
        'keep recoTracks_globalCosmicMuons_*_*', 
        'keep recoTrackExtras_globalCosmicMuons_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuons_*_*', 
        'keep recoTracks_tevMuons_*_*', 
        'keep recoTrackExtras_tevMuons_*_*', 
        'keep recoTracksToOnerecoTracksAssociation_tevMuons_*_*', 
        'keep recoMuons_muons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muons_*_*', 
        'keep recoTracks_globalCosmicSplitMuons_*_*', 
        'keep recoTrackExtras_globalCosmicSplitMuons_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicSplitMuons_*_*', 
        'keep recoMuons_splitMuons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_splitMuons_*_*', 
        'keep recoTracks_cosmicMuonsNoRPC_*_*', 
        'keep recoTrackExtras_cosmicMuonsNoRPC_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsNoRPC_*_*', 
        'keep recoTracks_globalCosmicMuonsNoRPC_*_*', 
        'keep recoTrackExtras_globalCosmicMuonsNoRPC_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuonsNoRPC_*_*', 
        'keep recoMuons_muonsNoRPC_*_*', 
        'keep recoTracks_cosmicMuons1Leg_*_*', 
        'keep recoTrackExtras_cosmicMuons1Leg_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuons1Leg_*_*', 
        'keep recoTracks_globalCosmicMuons1Leg_*_*', 
        'keep recoTrackExtras_globalCosmicMuons1Leg_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuons1Leg_*_*', 
        'keep recoMuons_muons1Leg_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muons1Leg_*_*', 
        'keep recoTracks_cosmicMuonsWitht0Correction_*_*', 
        'keep recoTrackExtras_cosmicMuonsWitht0Correction_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsWitht0Correction_*_*', 
        'keep recoTracks_globalCosmicMuonsWitht0Correction_*_*', 
        'keep recoTrackExtras_globalCosmicMuonsWitht0Correction_*_*', 
        'keep TrackingRecHitsOwned_globalCosmicMuonsWitht0Correction_*_*', 
        'keep recoMuons_muonsWitht0Correction_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muonsWitht0Correction_*_*', 
        'keep recoTracks_cosmicMuonsEndCapsOnly_*_*', 
        'keep recoTrackExtras_cosmicMuonsEndCapsOnly_*_*', 
        'keep TrackingRecHitsOwned_cosmicMuonsEndCapsOnly_*_*', 
        'keep recoTracks_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep recoTrackExtras_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep TrackingRecHitsOwned_globalBeamHaloMuonEndCapslOnly_*_*', 
        'keep recoMuons_muonsBeamHaloEndCapsOnly_*_*', 
        'keep recoMuonTimeExtraedmValueMap_muonsBeamHaloEndCapsOnly_*_*', 
        'keep recoTracks_standAloneMuons_*_*', 
        'keep recoTrackExtras_standAloneMuons_*_*', 
        'keep TrackingRecHitsOwned_standAloneMuons_*_*', 
        'keep recoMuons_lhcSTAMuons_*_*', 
        'keep recoMuonTimeExtraedmValueMap_lhcSTAMuons_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5_*_*', 
        'keep recoTracks_ctfWithMaterialTracksBeamHaloMuon_*_*', 
        'keep recoTracks_ctfWithMaterialTracksP5LHCNavigation_*_*', 
        'keep *_muIsoDepositTk_*_*', 
        'keep *_muIsoDepositCalByAssociatorTowers_*_*', 
        'keep *_muIsoDepositCalByAssociatorHits_*_*', 
        'keep *_muIsoDepositJets_*_*', 
        'keep *_muGlobalIsoDepositCtfTk_*_*', 
        'keep *_muGlobalIsoDepositCalByAssociatorTowers_*_*', 
        'keep *_muGlobalIsoDepositCalByAssociatorHits_*_*', 
        'keep *_muGlobalIsoDepositJets_*_*', 
        'keep *_offlineBeamSpot_*_*', 
        'keep  *_offlinePrimaryVertices__*', 
        'keep *_offlinePrimaryVerticesWithBS_*_*', 
        'keep *_offlinePrimaryVerticesFromCosmicTracks_*_*', 
        'keep *_nuclearInteractionMaker_*_*', 
        'keep *_generalV0Candidates_*_*', 
        'keep *_inclusiveSecondaryVertices_*_*', 
        'keep *_cscTriggerPrimitiveDigis_*_*', 
        'keep *_dtTriggerPrimitiveDigis_*_*', 
        'keep *_rpcTriggerDigis_*_*', 
        'keep *_rctDigis_*_*', 
        'keep *_csctfDigis_*_*', 
        'keep *_csctfTrackDigis_*_*', 
        'keep *_dttfDigis_*_*', 
        'keep *_gctDigis_*_*', 
        'keep *_gmtDigis_*_*', 
        'keep *_gtDigis_*_*', 
        'keep *_gtEvmDigis_*_*', 
        'keep *_l1GtRecord_*_*', 
        'keep *_l1GtTriggerMenuLite_*_*', 
        'keep *_l1GtObjectMap_*_*', 
        'keep *_l1extraParticles_*_*', 
        'keep *_l1L1GtObjectMap_*_*', 
        'keep LumiDetails_lumiProducer_*_*', 
        'keep LumiSummary_lumiProducer_*_*', 
        'drop *_hlt*_*_*', 
        'keep GlobalObjectMapRecord_hltGtStage2ObjectMap_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep triggerTriggerEvent_*_*_*', 
        'keep *_hltFEDSelectorL1_*_*', 
        'keep *_hltScoutingCaloPacker_*_*', 
        'keep *_hltScoutingEgammaPacker_*_*', 
        'keep *_hltScoutingMuonPackerCalo_*_*', 
        'keep *_hltScoutingMuonPacker_*_*', 
        'keep *_hltScoutingPFPacker_*_*', 
        'keep *_hltScoutingPrimaryVertexPackerCaloMuon_*_*', 
        'keep *_hltScoutingPrimaryVertexPacker_*_*', 
        'keep *_hltScoutingTrackPacker_*_*', 
        'keep edmTriggerResults_*_*_*', 
        'keep L1AcceptBunchCrossings_scalersRawToDigi_*_*', 
        'keep L1TriggerScalerss_scalersRawToDigi_*_*', 
        'keep Level1TriggerScalerss_scalersRawToDigi_*_*', 
        'keep LumiScalerss_scalersRawToDigi_*_*', 
        'keep BeamSpotOnlines_scalersRawToDigi_*_*', 
        'keep DcsStatuss_scalersRawToDigi_*_*', 
        'keep DcsStatuss_hltScalersRawToDigi_*_*', 
        'keep CTPPSRecord_onlineMetaDataDigis_*_*', 
        'keep DCSRecord_onlineMetaDataDigis_*_*', 
        'keep OnlineLuminosityRecord_onlineMetaDataDigis_*_*', 
        'keep recoBeamSpot_onlineMetaDataDigis_*_*', 
        'keep *_tcdsDigis_*_*', 
        'drop *_MEtoEDMConverter_*_*', 
        'drop *_*_*_SKIM'
     ) )
)

# Other statements
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:phase1_2021_cosmics', '')

# Path and EndPath definitions
process.raw2digi_step = cms.Path(process.RawToDigi)
process.L1Reco_step = cms.Path(process.L1Reco)
process.reconstruction_step = cms.Path(process.reconstructionCosmics)
process.endjob_step = cms.EndPath(process.endOfProcess)
process.FEVToutput_step = cms.EndPath(process.FEVToutput)
process.SKIMStreamCosmicSPOutPath = cms.EndPath(process.SKIMStreamCosmicSP)
process.SKIMStreamCosmicTPOutPath = cms.EndPath(process.SKIMStreamCosmicTP)

# Schedule definition
process.schedule = cms.Schedule(process.raw2digi_step,process.L1Reco_step,process.reconstruction_step,process.cosmicMuonsBarrelOnlyTkPath,process.cosmicMuonsEndCapsOnlyTkPath,process.cosmicMuonsTkPath,process.cosmicMuons1LegTkPath,process.globalCosmicMuonsBarrelOnlyTkPath,process.globalCosmicMuonsEndCapsOnlyTkPath,process.globalCosmicMuonsTkPath,process.globalCosmicMuons1LegTkPath,process.cosmictrackfinderP5TkCntPath,process.ctfWithMaterialTracksP5TkCntPath,process.cosmicMuonsBarrelOnlyPath,process.cosmicMuonsPath,process.cosmicMuons1LegPath,process.globalCosmicMuonsBarrelOnlyPath,process.cosmictrackfinderP5Path,process.globalCosmicMuonsPath,process.globalCosmicMuons1LegPath,process.endjob_step,process.FEVToutput_step,process.SKIMStreamCosmicSPOutPath,process.SKIMStreamCosmicTPOutPath)
from PhysicsTools.PatAlgos.tools.helpers import associatePatAlgosToolsTask
associatePatAlgosToolsTask(process)

#do not add changes to your config after this point (unless you know what you are doing)
from FWCore.ParameterSet.Utilities import convertToUnscheduled
process=convertToUnscheduled(process)


# Customisation from command line

#Have logErrorHarvester wait for the same EDProducers to finish as those providing data for the OutputModule
from FWCore.Modules.logErrorHarvester_cff import customiseLogErrorHarvesterUsingOutputCommands
process = customiseLogErrorHarvesterUsingOutputCommands(process)

# Add early deletion of temporary data products to reduce peak memory need
from Configuration.StandardSequences.earlyDeleteSettings_cff import customiseEarlyDelete
process = customiseEarlyDelete(process)
# End adding early deletion
